# conf/config.yaml
experiment_name: densenet_pets
seed: 159753

# device / runtime
device: cuda
amp: true # mixed precision
compile: true

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true

data:
  root: data/
  img_size: 224
  batch_size: 64
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  val_split: 0.10
  download: true

model:
  growth_rate: 32
  block_layers: [6, 12, 24, 16]
  compression: 0.5
  init_features: 64
  dropout: 0.0
  num_classes: 37

optim:
  name: adamw
  lr: 3e-4
  weight_decay: 1e-4
  betas: [0.9, 0.999]
  momentum: 0.9
  nesterov: true

sched:
  name: cosine                 # or "step"
  T_max: ${trainer.epochs}
  eta_min: 1.0e-6
  warmup_epochs: 5
  warmup_lr: 1.0e-6
  # If using step schedule instead:
  step_size: 30
  gamma: 0.1

trainer:
  epochs: 100
  log_interval: 50
  val_interval: 1
  grad_clip_norm: 1.0
  label_smoothing: 0.05
