# conf/config.yaml
experiment_name: densenet_pets
seed: 159753

# device / runtime
device: cuda
amp: true # mixed precision
compile: true

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true

data:
  root: data/
  img_size: 224
  batch_size: 128
  num_workers: 16
  pin_memory: true
  persistent_workers: true
  val_split: 0.10
  download: true

model:
  growth_rate: 32
  block_layers: [6, 12, 24, 16]
  compression: 0.5
  init_features: 64
  dropout: 0.0
  num_classes: 37
  separable_convs: False

optim:
  name: sgd
  lr: 0.1
  min_lr: 0.001
  weight_decay: 5e-4
  momentum: 0.9
  nesterov: true
  warmup_steps: 500

trainer:
  epochs: 50
  log_interval: 20
  val_interval: 1
  grad_clip_norm: 10.0
  label_smoothing: 0.05